source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.2'
use_frameworks!

target :'Trackify' do
    pod 'AWSCognito'
    pod 'AWSCognitoIdentityProvider'
    pod 'AWSDynamoDB'
    pod 'AWSEC2'
    pod 'AWSLambda'
    pod 'AWSS3'
    pod 'AWSSES'
    pod 'AWSSimpleDB'
    pod 'AWSSNS'
end